[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Ensures that it applies to files that exist as well, generally good for SPAs

[[redirects]]
  from = "/script.js"
  to = "/script.js"
  status = 200
  force = true # Ensures that it serves the file directly even if the above rule might try to catch it.

[[redirects]]
  from = "/style.css"
  to = "/style.css"
  status = 200
  force = true # Same as above for CSS
